# Waveshare mmWave reuires 50mA power. 
# reference: https://www.waveshare.com/wiki/HMMD_mmWave_Sensor
# Bosche BME688 average power consumption during gas scaning is 3.9 mA
# reference: https://www.bosch-sensortec.com/products/environmental-sensors/gas-sensors/bme688/#technical
#
# every 3 minutes scan the room.
scan_interval : 180000
# every x scans, must update with environmental data points to mqtt regardless of detected movements.
heartbeat_update: 10
# reboot periodically in case of memory leaks. 
reboot_cycle: 480
# reboot if retries failed.
wifi_retry: 5
#
device : "RaspberryPi Pico 2W/bme688"
station : "bedroom"
# mmWave
tx_pin : 4
rx_pin : 5
uart : 1
baudrate: 115200
# scan the room for 9 seconds.
mmwave_scan_period: 9000
# bme688
# could be 0x76 or 0x77, enter decimal equivalent below. check device scanner printout to debug.
bme_i2c: 118
# how long to survey the room. the results are affected by the onboard heater of bme68x sensor.
bme_scan_period: 15000
bme_temp_offset: 2.5
sda: 2 
scl: 3
power_pin : 22
# connections
wifi:
    ssid : "<SSID>"
    psk  : "<WIFI_PASSWORD>"
    country: "ca"
mqtt:
   broker : "io.adafruit.com"
   port: 8883
   uid : "ADAFRUIT_AIO_USERNAME"
   pwd : "ADAFRUIT_AIO_KEY"
   topic : "<ADAFRUIT_AIO_USERNAME>/feeds/<ADAFRUIT_AIO_KEY>"
